export const types = {
  INIT_BOARD: 'INIT_BOARD',
  ADD_STEP: 'ADD_STEP',
  SWITCH_PLAYER: 'SWITCH_PLAYER',
  GO_TO_STEP: 'GO_TO_STEP',
  ADD_HISTORY: 'ADD_HISTORY',
  REPLAY: 'REPLAY',
  SWITCH_SORT: 'SWITCH_SORT',
  SET_WINNER: 'SET_WINNER',
  LOGIN: 'LOGIN',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_ERR: 'LOGIN_ERR',
  REGISTER: 'REGISTER',
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  LOGOUT: 'LOGOUT',
  CALLBACKLINK: 'CALLBACKLINK',
  CONNECT: 'CONNECT',
  SET_COMPETITOR: 'SET_COMPETITOR',
  REMOVE_COMPETITOR: 'REMOVE_COMPETITOR',
  SWITCH_PLAYER_ONLINE: 'SWITCH_PLAYER_ONLINE',
  REQUEST_UNDO: 'REQUEST_UNDO',
  ACCEPT_UNDO: 'ACCEPT_UNDO',
  VISIBLE_MODAL: 'VISIBLE_MODAL',
  HIDE_MODAL: 'HIDE_MODAL',
  SET_REQUEST_UNDO: 'SET_REQUEST_UNDO',
  SET_REQUEST_REPLAY: 'SET_REQUEST_REPLAY',
  SWITCH_IS_SEARCHING: 'SWITCH_IS_SEARCHING',
  ADD_CHAT: 'ADD_CHAT',
  REMOVE_CHAT: 'REMOVE_CHAT',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  SWITCH_IS_CHANGE_PASSWORD: 'SWITCH_IS_CHANGE_PASSWORD',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  UPLOAD_AVATAR: 'UPLOAD_AVATAR',
  GET_INFO: 'GET_INFO',
  UPDATE_INFO: 'UPDATE_INFO',
  UPDATE_INFO_ERR: 'UPDATE_INFO_ERR',
  CHANGE_PASSWORD_ERR: 'CHANGE_PASSWORD_ERR',
  SWITCH_LOADING: 'SWITCH_LOADING',
  SET_IMAGE_URL: 'SET_IMAGE_URL',
  LOGIN_FB: 'LOGIN_FB',
  SET_REQUEST: 'SET_REQUEST',
  SWITCH_LEVEL: 'SWITCH_LEVEL'
};

export const numberCell = 20;

export const players = {
  X: 'X',
  O: 'O'
};

export const sort = {
  Asc: true,
  Desc: false
};

export const api_url = 'https://btcn06-1612685.herokuapp.com';

export const id = {
  GOOGLE_CLIENT_ID:
    '163647069051-rsjk73osi31tai0rd8r1idn3rqar7l4u.apps.googleusercontent.com',
  FACEBOOK_APP_ID: '965882247126379'
};
